### ISSUE TITLE
1.0.1.yml No requirement to support historic versions of claim

### ISSUE THREAD

**Issue by edmolyneux** [Property-Data-Trust-Framework/api#5]
https://github.com/Property-Data-Trust-Framework/api/blob/196423fdfd02b2ad7aa256da251740062cdfae2c/pdtf-baseline-api-1.0.1.yml#L130-L174

This is already implemented in the request for property claims by supplying a path in the query

**Comment by Reynodes** [comment]
This is the default in the DLT system. So historic version will be there, and it will be useful to be able to view audit trail
